# Generated by Django 5.2.16 on 2026-09-22 02:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_member_signature'),
        ('savings', '0006_seed_regular_savings_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersavingsaccount',
            name='is_joint',
            field=models.BooleanField(db_index=True, default=False, help_text='Shared by the primary member and one or more joint co-owners.'),
        ),
        migrations.AlterField(
            model_name='membersavingsaccount',
            name='member',
            field=models.ForeignKey(help_text='Primary account holder.', on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to='members.member'),
        ),
        migrations.CreateModel(
            name='SavingsJointOwner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_owner_links', to='savings.membersavingsaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_joint_owner_links', to='members.member')),
            ],
            options={
                'verbose_name': 'Savings joint owner',
                'verbose_name_plural': 'Savings joint owners',
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='membersavingsaccount',
            name='joint_owners',
            field=models.ManyToManyField(blank=True, help_text='Additional members on a joint savings account (not the primary).', related_name='joint_savings_accounts', through='savings.SavingsJointOwner', to='members.member'),
        ),
        migrations.AddConstraint(
            model_name='savingsjointowner',
            constraint=models.UniqueConstraint(fields=('account', 'member'), name='savings_joint_owner_unique'),
        ),
    ]
