# Generated by Django 5.2.16 on 2026-09-25 01:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_savingsproduct_interest_apply_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Yearly multiplier. Interest = savings × this rate × months ÷ 12. Example: 0.070 on ₱2,000 every 3 months = 2,000 × 0.070 × 3 ÷ 12 = ₱35.00.', max_digits=6),
        ),
    ]
