# Generated by Django 5.2.3 on 2026-09-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palay_trade', '0007_enable_palay_utang_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palaytradeproduct',
            name='code',
            field=models.SlugField(help_text='Short unique code: rice-palay or bigas.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='palaytradeproduct',
            name='name',
            field=models.CharField(help_text='Display name — use Rice Palay or Bigas.', max_length=150),
        ),
    ]
