# Generated by Django 5.2.3 on 2026-09-20 13:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_disbursement_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Interest rate as a monthly decimal (e.g. 0.015 = 1.5%) for this application. Daily interest = (rate ÷ 30) × remaining principal. Interest is computed when a payment is recorded with usable dates, not at apply time. Falls back to the loan product rate when blank.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='usable_days',
            field=models.PositiveIntegerField(blank=True, help_text='Calendar span stored at apply time. Interest is not charged from this value; staff enter usable dates when recording a payment.', null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='usable_from',
            field=models.DateField(blank=True, help_text='Application date. First payment interest period starts here.', null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='usable_to',
            field=models.DateField(blank=True, help_text='Kept for history. Interest is computed at payment time, not apply time.', null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Legacy product default late-payment interest rate as a monthly decimal (e.g. 0.015 = 1.5%). The rate used for each loan is set on the application at apply time. Daily interest = (rate ÷ 30) × principal.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest for this usable-days period on balance left to pay: (rate ÷ 30) × outstanding balance × usable_days (rounded). ₱0 when the loan has no remaining balance.', max_digits=12),
        ),
    ]
