# Generated by Django 5.2.16 on 2026-09-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_alter_loanapplication_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansettings',
            name='min_membership_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, members must wait the minimum membership months below before they can request a loan. When disabled, any member can apply immediately (the months value is ignored).'),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='min_membership_months',
            field=models.PositiveIntegerField(default=3, help_text='Minimum months a member must be registered before they can request a loan. Example: 3 means a member who joined only 1 week ago cannot apply yet. Only used when the waiting-period rule above is enabled. Set to 0 to allow loan requests immediately even when the rule is on.'),
        ),
    ]
