# Generated by Django 5.2.16 on 2026-09-24 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_loandocumentation_comaker_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insurance withheld at disbursement (principal × 0.66%).', max_digits=12),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest withheld at disbursement (principal × rate × months_pay / 12).', max_digits=12),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='months_pay',
            field=models.PositiveIntegerField(blank=True, help_text='Months used to prorate interest: principal × rate × (months_pay / 12).', null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Savings withheld at disbursement (staff-entered amount).', max_digits=12),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='share_capital_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Share capital withheld at disbursement (principal × 2%).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='other_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy/other fees withheld at disbursement.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee withheld at disbursement (principal × 2%).', max_digits=12),
        ),
    ]
