# Generated by Django 5.2.16 on 2026-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0025_disbursement_formula_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansettings',
            name='usable_days_editable',
            field=models.BooleanField(default=False, help_text='When enabled, staff can type the interest-period Days on the payment form (To date updates from From + Days). When disabled, Days is locked and computed automatically as To − From.'),
        ),
    ]
