# Generated by Django 5.2.16 on 2026-09-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_loansettings_usable_days_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='uses_usable_days',
            field=models.BooleanField(default=False, help_text='When enabled, this product uses usable-days interest: interest = principal × rate × (usable days ÷ 360). When disabled, the product uses the normal loan path (no usable-days period interest).'),
        ),
    ]
