# Generated by Django 5.2.16 on 2026-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_loanproduct_uses_usable_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='interest_start_month',
        ),
    ]
