# Generated by Django 5.2.16 on 2026-09-25 08:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_remove_loanproduct_interest_start_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest withheld at disbursement (principal × product rate × months_pay).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='months_pay',
            field=models.PositiveIntegerField(blank=True, help_text='Months used to compute interest: principal × product rate × months_pay.', null=True),
        ),
    ]
