# Generated by Django 5.2.16 on 2026-09-25 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_disbursement_monthly_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest withheld at disbursement (principal × product rate × months_pay / 12).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='months_pay',
            field=models.PositiveIntegerField(blank=True, help_text='Months used in interest: principal × product rate × (months_pay / 12).', null=True),
        ),
    ]
