# Generated by Django 5.2.16 on 2026-09-25

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0030_disbursement_interest_over_12"),
        ("savings", "0018_savingsbeneficiary_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement",
            name="savings_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Member savings account that receives the withheld savings.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_disbursements",
                to="savings.membersavingsaccount",
            ),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="savings_credit",
            field=models.OneToOneField(
                blank=True,
                help_text="Deposit posted to the member's savings for the withheld amount.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_disbursement",
                to="savings.savingstransaction",
            ),
        ),
        migrations.AlterField(
            model_name="disbursement",
            name="savings_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Savings withheld at disbursement and deposited to the member's savings account.",
                max_digits=12,
            ),
        ),
    ]
