# Generated by Django 5.2.3 on 2026-09-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_member_status_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approval date'),
        ),
        migrations.AddField(
            model_name='member',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Approved by (Chairperson)'),
        ),
        migrations.AddField(
            model_name='member',
            name='business_cellular',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Cellular phone no.'),
        ),
        migrations.AddField(
            model_name='member',
            name='business_telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telephone no.'),
        ),
        migrations.AddField(
            model_name='member',
            name='complete_business_name_address',
            field=models.TextField(blank=True, default='', verbose_name='Complete business name / address'),
        ),
        migrations.AddField(
            model_name='member',
            name='home_address',
            field=models.TextField(blank=True, default='', verbose_name='Home (mailing) / present / permanent address'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Membership number'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='member',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='recorded_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Recorded by (Cooperative Secretary)'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Spouse age'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_cellular',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Spouse cell. phone no.'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Spouse date of birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_employer_address',
            field=models.TextField(blank=True, default='', verbose_name='Employer / business address'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_employer_business',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name of employer / business'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spouse first name'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=20, verbose_name='Spouse gender'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spouse surname'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spouse middle name'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Spouse telephone no.'),
        ),
        migrations.AddField(
            model_name='member',
            name='thumb_mark',
            field=models.ImageField(blank=True, null=True, upload_to='members/thumb_marks/', verbose_name='Right hand thumb mark'),
        ),
        migrations.AlterField(
            model_name='member',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monthly salary / annual income'),
        ),
        migrations.AlterField(
            model_name='member',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('elementary', 'Elementary'), ('high_school', 'High School'), ('college_level', 'College Level'), ('college_grad', 'College Grad.'), ('post_graduate', 'Post Graduate')], default='', max_length=150, verbose_name='Highest educ. attainment'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='income_sources',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Business / occupation / source of income'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membertype'),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cellular no.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resolution_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BOD Resolution No.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, default='', help_text='Auto-filled from spouse name parts when those are set.', max_length=200, verbose_name='Name of spouse (full)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse_occupation',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Spouse occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tin',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tax identification no.'),
        ),
        migrations.CreateModel(
            name='MemberBeneficiaryDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('is_dependent', models.BooleanField(default=False, verbose_name='Dependent')),
                ('is_beneficiary', models.BooleanField(default=False, verbose_name='Beneficiary')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries_dependents', to='members.member')),
            ],
            options={
                'verbose_name': 'Beneficiary / dependent',
                'verbose_name_plural': 'Beneficiaries / dependents',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
