# Generated by Django 5.2.3 on 2026-09-21 08:38

import django.db.models.deletion
from django.db import migrations, models


def seed_nationalities(apps, schema_editor):
    Nationality = apps.get_model("members", "Nationality")
    defaults = [
        ("filipino", "Filipino", 0),
        ("american", "American", 10),
        ("chinese", "Chinese", 20),
        ("japanese", "Japanese", 30),
        ("korean", "Korean", 40),
        ("indian", "Indian", 50),
        ("other", "Other", 999),
    ]
    for slug, name, sort_order in defaults:
        Nationality.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_membership_application_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this nationality from new assignments.')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.nationality', verbose_name='Nationality'),
        ),
        migrations.RunPython(seed_nationalities, noop_reverse),
    ]
