# Generated by Django 5.2.3 on 2026-09-21 08:39

from django.db import migrations


def seed_nationalities(apps, schema_editor):
    Nationality = apps.get_model("members", "Nationality")
    defaults = [
        ("filipino", "Filipino", 0),
        ("american", "American", 10),
        ("chinese", "Chinese", 20),
        ("japanese", "Japanese", 30),
        ("korean", "Korean", 40),
        ("indian", "Indian", 50),
        ("other", "Other", 999),
    ]
    for slug, name, sort_order in defaults:
        Nationality.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0030_nationality_model"),
    ]

    operations = [
        migrations.RunPython(seed_nationalities, noop_reverse),
    ]
