# Generated by Django 5.2.3 on 2026-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_seed_nationalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='members/signatures/', verbose_name='Signature over printed name'),
        ),
    ]
